source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'cosy' do
  platform :ios, '9.0'
  pod 'Alamofire', '3.2.1'
end

target 'cosy WatchKit Extension' do
  platform :watchos, '2.0'
  pod 'Alamofire', '3.2.1'
end
